### ISSUE TITLE
[Bug Report] `step` function in `franka_env.py` takes incorrect action

### ISSUE THREAD

**Issue by matinmoezzi** [Farama-Foundation/Gymnasium-Robotics#116]
Hi,
**Describe the bug**
The `step` function in `franka_env.py` takes incorrect action in the non-IK controller (https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/c9a2e3d810aa4da4a601b994ee00522c603f4eba/gymnasium_robotics/envs/franka_kitchen/franka_env.py#L144). First, it denormalizes the input action from [-1, 1] range to each actuators' control range, and then calls `do_simulation(action)` with the normalized actions which is incorrect. It should input the denormalized action into `do_simulation()`

**Code example**
`self.data.ctrl[:] = self.actuation_center + action * self.actuation_range`
`self.do_simulation(action, self.frame_skip)`
It should be:
`action = self.actuation_center + action * self.actuation_range`
`self.do_simulation(action, self.frame_skip)`

**Comment by rodrigodelazcano** [comment]
Thank you for bringing this up @matinmoezzi! I'll make the fixes to it.
