### ISSUE TITLE
[Bug] ImportError on MujocoRenderer from Gymnasium. 

### ISSUE THREAD

**Issue by R-Liebert** [Farama-Foundation/Gymnasium-Robotics#127]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

Getting an ImportError in gymnasium_robotics/envs/robot_env.py, line 282. Error: ImportError: cannot import name 'MujocoRenderer' from 'gymnasium.envs.mujoco.mujoco_rendering.py

**Code example**
import gymnasium as gym
env = gym.make("FetchPushDense-v2")

**System Info**
Describe the characteristic of your environment:
Latest gymnasium and gymnasium-robotics by pip. Mujoco-2.3.2 tested with both source and pip

Ubuntu 18.04

Tested with python 3.7 and 3.10.9

**Additional context**
Might be a issue in Gymnasium and not Gymnasium-Robotics.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gymnasium-robotics/issues) in the repo (**required**)

**Comment by rodrigodelazcano** [comment]
Hi @R-Liebert , I'm not able to replicate your issue. Can you specify the versions of gymnasium and gymnasium-robotics you are using. The following versions work for me:

`gymnasium` == 0.27.1
`gymnasium-robotics` == 1.2.0
