### ISSUE TITLE
[Question]  How can I add another point in point.xml file?

### ISSUE THREAD

**Issue by hanshuo-shuo** [Farama-Foundation/Gymnasium-Robotics#134]
Hello, 

I'm doing multiagent research and wonder how to add another ball into the maze envs.

It seems that I need to change the `point.xml` file but I'm having problems rendering it after the change to this file.

Thank you so much!

**Comment by Kallinteris-Andreas** [comment]
First you will need to change the environment, to use a `PettingZoo` API, and then instantiate the `point.xml` object multiple times.

**Comment by rodrigodelazcano** [comment]
@hanshuo-shuo did you manage to create your model? What kind of issues were you facing when rendering?
