### ISSUE TITLE
[Question] pip install gymnasium-robotics[mujoco-py]

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium-Robotics#140]
Hi!

When I use this command `pip install gymnasium-robotics[mujoco-py]`,  

`no matches found: gymnasium-robotics[mujoco-py]` is displayed.

Is this installation correct and still available?

Thanks!

**Comment by Kallinteris-Andreas** [comment]
try `pip install 'gymnasium-robotics[mujoco_py]'`
