### ISSUE TITLE
[Question] Lib version mismatch?

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium-Robotics#144]
### Question

Hi!

I'm working with `FrankaKitchen-v1` env and notice that the `action` which is not denormalized is passed to the function `do_simulation` in `franka_env.py` in my virtual env.

```
# Denormalize the input action from [-1, 1] range to the each actuators control range
self.data.ctrl[:] = self.actuation_center + action * self.actuation_range
self.do_simulation(action, self.frame_skip)
if self.render_mode == "human":
    self.render()
```

Meanwhile, in [this line](https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/ece22965689cdda91af3392f91f6c94cab0c847b/gymnasium_robotics/envs/franka_kitchen/franka_env.py#L144), the denormalized action is correctly passed to the function `do_simulation`.

I have installed the main branch of `Gymnasium-Robotics` by `pip install` and the version is 1.2.0, but why the corresponding code snippet is different?

**Comment by Kallinteris-Andreas** [comment]
It will be fixed next release
it was fixed this commit:
https://github.com/Farama-Foundation/Gymnasium-Robotics/commit/fa991f3387b80f67dd80786e98710d5922e71a11

**Comment by Kallinteris-Andreas** [comment]
@QUIlToT you can use the git version in the meantime
