### ISSUE TITLE
[Question] Wall Contact in PointMaze

### ISSUE THREAD

**Issue by AhmedMagdyHendawy** [Farama-Foundation/Gymnasium-Robotics#152]
I am working with the PointMaze environments from D4RL. I noticed that the point can partially go through walls. In addition, the point has slightly emerged under the floor. Is that intentional?

**Comment by rodrigodelazcano** [comment]
Hi @AhmedMagdyHendawy. Yes this is intentional, the green and read spheres are used for visualization purposes (they are not bodies) of the agent and the goal. The point agent and the goal are at the center of those spheres.
