### ISSUE TITLE
[Bug Report] AntEnv obs[:2] is not x, y but z coordinate and x-orientation

### ISSUE THREAD

**Issue by llewynS** [Farama-Foundation/Gymnasium-Robotics#181]
**Describe the bug**
The _get_obs function does the following transformation to the observation space
        achieved_goal = ant_obs[:2]
        observation = ant_obs[2:]
But reading AntEnv V4 the pos 0 and pos 1 observations are not the final x and y coordinates. As the antenv is directly queried and no computation is done in the environment it's clear that this is an error.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gymnasium-robotics/issues) in the repo (**required**)

**Comment by Kallinteris-Andreas** [comment]
the first 2 are the X&Y coordinates of the `torso`
https://gymnasium.farama.org/main/environments/mujoco/ant/#observation-space

**Comment by llewynS** [comment]
From your link this is not correct. First two are the z coordinate and the x-orientation as I stated.
![image](https://github.com/Farama-Foundation/Gymnasium-Robotics/assets/5723347/ba35198f-b673-4c94-8003-8dd98b0d1850)

**Comment by Kallinteris-Andreas** [comment]
Read the description above the table (and the excluded observations are in the bottom of the table)
