### ISSUE TITLE
[Question] Is there a way to set the environment to a specific state in franka kitchen tasks?

### ISSUE THREAD

**Issue by ygtkorkmaz** [Farama-Foundation/Gymnasium-Robotics#182]
I am trying to replay the expert demonstrations in the franka kitchen environment but I couldn't find any way of setting the environment to a specific state in the code.  Any help would be appreciated!

**Comment by Kallinteris-Andreas** [comment]
Set the values in 
```py
env.unwrapped.data.qpos
env.unwrapped.data.qvel
```

more info how mujuco state works can be found here: https://mujoco.readthedocs.io/en/latest/computation/index.html#the-state

**Comment by ygtkorkmaz** [comment]
Got it, thanks a lot. Also, I realized envs in gymnasium-robotics don't have a get_dataset() function. I believe I should get the dataset using Minari?

**Comment by Kallinteris-Andreas** [comment]
yes, this project only have robotic environments, for offline RL you need to use minari

**Comment by ygtkorkmaz** [comment]
Great, thank you so much!
