### ISSUE TITLE
[Question] Can I set the initial position / goal position for the gripper of the Fetch robot?

### ISSUE THREAD

**Issue by RajGhugare19** [Farama-Foundation/Gymnasium-Robotics#188]
### Question

Similar to how, we could set the goal and reset "tile" locations in the pointmaze and antmaze environment, can I set if for the FetchReach robot as well?

**Comment by rodrigodelazcano** [comment]
No, we currently don't have that functionality, but it would be a great addition to the Fetch environments. Would you be interested on making a PR with this feature?

**Comment by RajGhugare19** [comment]
I would be, but I am not sure were to start. If you know the high level path towards adding this feature, then I can code the low level details.

**Comment by Kallinteris-Andreas** [comment]
This feature is already included in `Gymnasium-Robotics`, you can use the `initial_qpos` argument.
