### ISSUE TITLE
[Bug Report] Minor User Warning : WARN: Overriding environment HandManipulateBlockRotateZ-v1 already in registry.

### ISSUE THREAD

**Issue by leonasting** [Farama-Foundation/Gymnasium-Robotics#19]
**Describe the bug**
Getting user warning  UserWarning: WARN: Overriding environment HandManipulateBlockRotateZ-v1 already in registry.
when importing Gym.
**Code example**

**System Info**
Describe the characteristic of your environment:
gym 0.26
python 3.10
windows
 * Python version
### Checklist

![image](https://user-images.githubusercontent.com/14107965/191357860-9115fd5d-ea43-4354-b6f1-ee97488a5cb5.png)
Updating the init file will fix it.

**Comment by rodrigodelazcano** [comment]
Thank you @leonasting for notifying. Will you be able to make a PR with the changes?

**Comment by leonasting** [comment]
Yes, I have created a request. Pull https://github.com/Farama-Foundation/Gym-Robotics/pull/20
