### ISSUE TITLE
[Bug Report] Environment toctrees menus are not being populated in 1.3

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium-Robotics#239]
In version 1.3 the environment, toctrees are not being populated:
![image](https://github.com/user-attachments/assets/9a8d948c-88ac-4a1a-bf28-225273ece213)

but in 1.2.4 everything works fine:
![image](https://github.com/user-attachments/assets/1259291a-8cc7-404a-829f-98e52fc01964)

@mgoulao

**Comment by Kallinteris-Andreas** [comment]
I have fucked up the registrations of envs during import
I am closing till i fix that, and i will re-open if the issue is not fixed by then

**Comment by Liang-ZX** [comment]
Same question

> In version 1.3 the environment, toctrees are not being populated: ![image](https://private-user-images.githubusercontent.com/30759571/375597657-9a8d948c-88ac-4a1a-bf28-225273ece213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMzUyODcsIm5iZiI6MTcyOTAzNDk4NywicGF0aCI6Ii8zMDc1OTU3MS8zNzU1OTc2NTctOWE4ZDk0OGMtODhhYy00YTFhLWJmMjgtMjI1MjczZWNlMjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Y2YyOGJkMTUyYzI1OGFlYTAyZmZhZDk5MGZhMDVkZTk1NmEzNGM0NDAyOTFjN2JlYTY3OWJkMjJjN2M3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qb2LMHo1bwXNe0RBRs_i2wmnP_t0jvDra04-x4zBXlw)
> 
> but in 1.2.4 everything works fine: ![image](https://private-user-images.githubusercontent.com/30759571/375597966-1259291a-8cc7-404a-829f-98e52fc01964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMzUyODcsIm5iZiI6MTcyOTAzNDk4NywicGF0aCI6Ii8zMDc1OTU3MS8zNzU1OTc5NjYtMTI1OTI5MWEtOGNjNy00MDRhLTgyOWYtOThlNTJmYzAxOTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNjQ5OWQ4YTk4MDg3NjVhZTNlNDVkNDNmMWE5NTA4NjY4YzgzMTk1MWExOTg4ZWZhNTJmNDMxNzBlODM0MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iGLM_Xm0JUV0-IseDCAV91Gg3B5Zh54P5xtgDLliPQA)
> 
> @mgoulao

Hi, I meet the same problem. Where can I find the doc for v1.2.4?

**Comment by Kallinteris-Andreas** [comment]
Bottom left of the docemtation website

**Comment by Liang-ZX** [comment]
Thank you so much.

**Comment by Kallinteris-Andreas** [comment]
fixed https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/254
will be fixed next release, in the meantime you can use `main` branch (on the bottom left)
