### ISSUE TITLE
[Question] Compatibility with stable-baselines3

### ISSUE THREAD

**Issue by simonguist** [Farama-Foundation/Gymnasium-Robotics#40]
### Question

Hi,
how do I initialize a gymnasium-robotics environment such that it is compatible with stable-baselines3. E.g., I tried: 
```
def make_env():
    env = gymnasium.make('FetchSlide-v2')
    return env
env = stable_baselines3.common.vec_env.DummyVecEnv([make_env])
```
which returns an error:
```
  File "/path/to/stable-baselines3/stable_baselines3/common/vec_env/util.py", line 68, in obs_space_info
    assert not hasattr(obs_space, "spaces"), f"Unsupported structured space '{type(obs_space)}'"
AssertionError: Unsupported structured space '<class 'gymnasium.spaces.dict.Dict'>'
```
I found this repo from Rodrigo de Lazcano: [validate-mujoco-bindings-gym-robotics](https://github.com/rodrigodelazcano/validate-mujoco-bindings-gym-robotics). However, it seems to use an older version of gymnasium-robotics (gym-robotics).
I couldn't find any more recent examples or documentation.

**Comment by qgallouedec** [comment]
This error is related to SB3 and not to gymnasium-robotics.
To answer your question, SB3 is not yet compatible with gymnasium. See https://github.com/DLR-RM/stable-baselines3/pull/780.
