### ISSUE TITLE
[Proposal] Add pydocstyle to pre-commit

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium-Robotics#57]
Pre-commit is missing pydocstyle check which is helpful for ensuring high quality documented code

**Comment by Kallinteris-Andreas** [comment]
Yes, Please, it would help me, with developing MaMuJoCo

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts or @rodrigodelazcano close
