### ISSUE TITLE
[Bug Report] pip mamujoco install error

### ISSUE THREAD

**Issue by sebidoe** [Farama-Foundation/Gymnasium-Robotics#95]
**Describe the bug**
I tried installing the mamujoco environement and pip reports that the extra "mamujoco" is not provided by gymnasium-robotics

**Code example**
pip install gymnasium-robotics[mamujoco]

WARNING: gymnasium-robotics 1.2.0 does not provide the extra 'mamujoco'

**System Info**
Describe the characteristic of your environment:
 * gymnasium was installed with pip
 * OS Version: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
 * Python 3.10

**Additional context**

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gymnasium-robotics/issues) in the repo

**Comment by rodrigodelazcano** [comment]
Hi! We haven't included `mamujoco` environments in the current `1.2.0` release. We are waiting to perform some evaluation test before making a new release. Other than that, the documentation has to also be updated and remove the custom dependency installation for `mamujoco`. In the future the dependencies will be included with a normal pip installation `pip install gymnasium-robotics`. 

For now the environments have to be installed from source:

```
git clone https://github.com/Farama-Foundation/Gymnasium-Robotics.git
cd Gymnasium-Robotics
pip install -e.
```

I'll make a PR with a documentation update and leave this thread open until the next release is made.

**Comment by Kallinteris-Andreas** [comment]
@rodrigodelazcano close
